const Router = require("express");
const router = new Router();
const deviceRouter = require("./deviceRouter");
const userRouter = require("./userRouter");
const brandRouter = require("./brandRouter");
const typeRouter = require("./typeRouter");
const basketRouter = require("./basketRouter");
const addressRouter = require("./addressRouter");
const personalInfoRouter = require("./personalInfoRouter");
const discount = require("./discountRouter");
const order = require("./orderRouter");
const stripe = require("./stripeRouter");
router.use("/user", userRouter);
router.use("/type", typeRouter);
router.use("/brand", brandRouter);
router.use("/device", deviceRouter);
router.use("/basket", basketRouter);
router.use("/address", addressRouter);
router.use("/personalInfo", personalInfoRouter);
router.use("/discount", discount);
router.use("/stripe", stripe);
router.use("/order", order);
module.exports = router;
